### PR TITLE
C++ AXI adapter library for RTL simulations

### PR DESCRIPTION
**Pull request by jonas-kaufmann**
We need AXI adapters for every piece of RTL that we are simulating with Verilator, e.g. Corundum, VTA, and the JPEG decoder. This PR adds a clean C++ library that _should_ properly respect the AXI standard, something that is not true about the hacked-up solutions we employ so far. The current solutions also don't respect the semantics of non-blocking assignments, which leads to many unpredictable issues we already have to hack around.

This AXI library also generalizes to any data, address and ID bus width. Overall, I tried to keep things simple, which might mean that we need to add small additional features in the future like supporting other modes besides incremental bursts and actually using the `wstrb` values. For the accelerators I looked at (JPEG decoder, VTA) all features are implemented.

Take a look at the JPEG decoder for an example on how to use this new AXI library. There's a bit of code that you need to [add in the header](https://github.com/jonas-kaufmann/simbricks-lpn/blob/692db227da9daf7deba9e916dee6aab755e9fbc5/sims/misc/jpeg_decoder/include/jpeg_decoder_verilator.hh), where you pass in the necessary signals from the RTL. Further, there are some functions that need to be implemented. Finally, [in the main simulation loop](https://github.com/jonas-kaufmann/simbricks-lpn/blob/692db227da9daf7deba9e916dee6aab755e9fbc5/sims/misc/jpeg_decoder/jpeg_decoder_verilator.cc#L377-L387), you just need to call `step()` and `step_apply()`.

@marvin71 @q713 I've added you mostly to look at the C++ side of things to check whether things look proper. I don't expect you to read the source code in detail.

@FreakyPenguin Also feel free to only take a high-level look. Since there are no changes to any existing hardware in the SimBricks repo yet, there's nothing that could break.

@A1248198 You can use these adapters to properly implement Corundum. Take a look at the examples I've linked above. Feel free to leave comments on this PR. It'd be good to update Corundum in the SimBricks repo to use this new AXI adapter library. If you have to do that anyway, feel free to open a PR for your changes.

@MJChku Feel free to leave comments as well.

### CODE REVIEW

**Comment by FreakyPenguin** [comment]
I have not looked closely yet, but both files seem to be in the `experiments` directory, despite what the commit message says

**Comment by jonas-kaufmann** [comment]
> I have not looked closely yet, but both files seem to be in the `experiments` directory, despite what the commit message says

Oups. That must have happened adopting the commits from the [simbricks-lpn](https://github.com/jonas-kaufmann/simbricks-lpn) repo. Let me fix that. I'm also going to fix the lint error.

**Review by FreakyPenguin — APPROVED** [review]
No objections, although as you suggested I have not reviewed in detail. We can test as we use this I guess.

**Comment by jonas-kaufmann** [comment]
> No objections, although as you suggested I have not reviewed in detail. We can test as we use this I guess.

I definitely tested the JPEG decoder and VTA in detail 🙂. I also checked for proper behavior in the  waveform files to ensure that things work as expected.

**Pull request merged**
