### PR TITLE
doc: fix logo size to full width of container

### PR DESCRIPTION
**Pull request by FreakyPenguin**
For some reason the new logo defaults to 0x0 px in the sphinx theme.

### CODE REVIEW

**Comment by jonas-kaufmann** [comment]
> For some reason the new logo defaults to 0x0 px in the sphinx theme.

This might be an issue with the SVG itself. In https://github.com/simbricks/simbricks/pull/122, GitHub also showed a size of 0x0 in the changes view. Do we want to fix that instead?

**Comment by FreakyPenguin** [comment]
You are welcome to look into it if you like. But having the size depend on the browser-interpretation of an SVG in the rendering seems a bit dangerous in any case.

**Comment by jonas-kaufmann** [comment]
I just tested your changes in Firefox and they don't actually work for me. Instead, I now looked into what has changed on the SVG side compared to the old logo. Turns out that we are no longer setting the width and height attributes on the top-level `svg` tag. I'll add a commit to fix that.

**Comment by jonas-kaufmann** [comment]
We also no longer need the fix in the CSS. I tested both Chromium and Firefox for this.

**Review by jonas-kaufmann — APPROVED** [review]

**Pull request merged**
