### PR TITLE
pre-commit hook, linter, and type-checker for Python files

### PR DESCRIPTION
**Pull request by Kaufi-Jonas**
I am using the python package `pre-commit` to mange pre-commit hooks. They can be activated using `pre-commit install` in the root dir, which automatically fixes files when committing. Concretely these hooks include:
- syntax verifier for yaml files
- replacing all single quotes with double quotes in Python files
- a formatter for python doc strings
- yapf to format Python code, based on [Google's style guide](https://google.github.io/styleguide/pyguide.html)
- import sorter for Python, which alphabetically sorts and separates imports into categories
Next, I added a Makefile target for linting and type-checking Python code. The linter (pylint) uses the configuration provided by Google's style guide. I decided to go with pytype for the type-checker because it uses inference and instead of enforcing type annotations everywhere, uses them where available.

Finally, I additionally wrapped all of this in Github Actions and schedules it to run on commits to the main branch and pull requests. There are three such actions, one for pre-commit , linter and type-checker, respectively. A single action takes at maximum 1m 30s in my tests, so we should be fine running it on Github without running into any limits.

I have checked the outputs for pylint and pytype and already fixed some code for the latter. We still need to apply the pre-commit hooks to all files in the code base though by running `pre-commit run -a`.

### CODE REVIEW

**Comment by FreakyPenguin** [comment]
In general this looks good. But do I see this right and only the pre-commit action will currently be green and the other two are still red? If so I would suggest we first fix the issues so that the actions are green when we add them (or add them so they don't trigger automatically yet) and also only add lint-python to the main lint target once it passes without error. Until then just keep the lint-python target separate.

I have been working on fixing all the c/c++ lint options, so after I push that make lint without the python stuff would be green.

**Comment by FreakyPenguin** [comment]
Looking at this a bit more I would suggest also adding makefile targets for yapf and isort, two each: `lint-yapf` and `lint-isort` (that only check and return errors) and then `format-yapf` and `format-isort` that would also apply the changes. Just like we have `lint-cpplint` and `clang-format` (although the latter is not really consistent terminology-wise). Then once these pass we can also add them to the default lint target.

I know pre-commit also runs these, but I would like to have an easy way to run them manually as well.

**Comment by Kaufi-Jonas** [comment]
> In general this looks good. But do I see this right and only the pre-commit action will currently be green and the other two are still red? If so I would suggest we first fix the issues so that the actions are green when we add them (or add them so they don't trigger automatically yet) and also only add lint-python to the main lint target once it passes without error. Until then just keep the lint-python target separate.
> 
> I have been working on fixing all the c/c++ lint options, so after I push that make lint without the python stuff would be green.

Yes, currently pytype and pylint fail. I will fix them in a later pull request, didn't want to clutter up this one. Makes sense to keep the Makefile targets separate for now.



> Looking at this a bit more I would suggest also adding makefile targets for yapf and isort, two each: `lint-yapf` and `lint-isort` (that only check and return errors) and then `format-yapf` and `format-isort` that would also apply the changes. Just like we have `lint-cpplint` and `clang-format` (although the latter is not really consistent terminology-wise). Then once these pass we can also add them to the default lint target.
> 
> I know pre-commit also runs these, but I would like to have an easy way to run them manually as well.

Yes, I can do that.

**Comment by Kaufi-Jonas** [comment]
@FreakyPenguin Could you take a look at the two TODOs in `experiments/simbricks/runtime/distributed.py` I have added in https://github.com/simbricks/simbricks/pull/18/commits/bf1d7f61b9ce2aab3fb625139616bff285e4091a ? The attribute `nics` is missing the classes `HostSim` and `Experiment`. After that, all type issues should be resolved.

**Review by FreakyPenguin — APPROVED** [review]
Looks good, thanks!

**Pull request merged**
